import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  appShell: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#eef4e8",
  },
  screen: {
    flex: 1,
  },
  content: {
    padding: 16,
    gap: 16,
  },
  onboardingSafeArea: {
    flex: 1,
    backgroundColor: "#091017",
  },
  onboardingTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
  },
  onboardingBackButton: {
    minWidth: 56,
    paddingVertical: 8,
  },
  onboardingBackButtonPlaceholder: {
    minWidth: 56,
  },
  onboardingBackText: {
    color: "#cfd7df",
    fontSize: 15,
    fontWeight: "800",
  },
  onboardingStepText: {
    color: "#8291a1",
    fontSize: 13,
    fontWeight: "800",
  },
  onboardingProgressTrack: {
    height: 6,
    marginHorizontal: 20,
    borderRadius: 999,
    backgroundColor: "#17212c",
    overflow: "hidden",
  },
  onboardingProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#d83d57",
  },
  onboardingScroll: {
    flex: 1,
  },
  onboardingContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 28,
    gap: 26,
  },
  onboardingQuestion: {
    color: "#f5f7fb",
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "800",
    textAlign: "center",
  },
  onboardingSubtitle: {
    color: "#95a2b2",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600",
    textAlign: "center",
  },
  onboardingCard: {
    gap: 22,
    alignItems: "center",
  },
  onboardingResultGrid: {
    width: "100%",
    gap: 12,
  },
  onboardingResultCard: {
    width: "100%",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 8,
    backgroundColor: "#101a25",
    borderWidth: 1,
    borderColor: "#202f3f",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  onboardingResultLabel: {
    color: "#90a0b2",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  onboardingResultValue: {
    color: "#f5f7fb",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900",
  },
  onboardingIntroCard: {
    width: "100%",
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderRadius: 28,
    backgroundColor: "#101a25",
    borderWidth: 1,
    borderColor: "#1d2a38",
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  onboardingIntroEyebrow: {
    color: "#d83d57",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.1,
    textAlign: "center",
    textTransform: "uppercase",
  },
  onboardingToggleRow: {
    flexDirection: "row",
    gap: 12,
  },
  onboardingToggleChip: {
    minWidth: 82,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "#121c27",
    borderWidth: 1,
    borderColor: "#243242",
    alignItems: "center",
  },
  onboardingToggleChipActive: {
    backgroundColor: "#d83d57",
    borderColor: "#d83d57",
    shadowColor: "#d83d57",
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  onboardingToggleChipPressed: {
    transform: [{ scale: 0.97 }],
  },
  onboardingToggleText: {
    color: "#b8c2cd",
    fontSize: 13,
    fontWeight: "800",
  },
  onboardingToggleTextActive: {
    color: "#ffffff",
  },
  onboardingWheelWrap: {
    width: "100%",
    height: 304,
    position: "relative",
    justifyContent: "center",
  },
  onboardingWheel: {
    flex: 1,
  },
  onboardingWheelContent: {},
  onboardingWheelItem: {
    height: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingWheelItemPressed: {
    opacity: 0.88,
  },
  onboardingWheelValue: {
    color: "#5d6d7e",
    fontSize: 28,
    fontWeight: "700",
  },
  onboardingWheelValueActive: {
    color: "#ffffff",
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "900",
    textShadowColor: "rgba(216,61,87,0.35)",
    textShadowRadius: 14,
  },
  onboardingWheelMaskTop: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 112,
    backgroundColor: "rgba(9,16,23,0.94)",
    zIndex: 2,
  },
  onboardingWheelMaskBottom: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 112,
    backgroundColor: "rgba(9,16,23,0.94)",
    zIndex: 2,
  },
  onboardingWheelFocus: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 124,
    height: 56,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(216,61,87,0.6)",
    backgroundColor: "rgba(216,61,87,0.12)",
    shadowColor: "#d83d57",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  onboardingChoiceList: {
    width: "100%",
    gap: 14,
  },
  onboardingChoiceCard: {
    width: "100%",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 20,
    backgroundColor: "#121c27",
    borderWidth: 1,
    borderColor: "#243242",
    shadowColor: "#000000",
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  onboardingChoiceCardActive: {
    backgroundColor: "#161f2b",
    borderColor: "#d83d57",
    transform: [{ scale: 1.01 }],
    shadowColor: "#d83d57",
    shadowOpacity: 0.24,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  onboardingChoiceCardPressed: {
    transform: [{ scale: 0.985 }],
  },
  onboardingChoiceText: {
    color: "#d9e2ec",
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  onboardingChoiceTextActive: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  onboardingFooter: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 22,
    gap: 12,
    backgroundColor: "#091017",
  },
  onboardingProgressNote: {
    color: "#f4a9b5",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  onboardingRevealHint: {
    color: "#d7dee6",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  onboardingPrimaryButton: {
    backgroundColor: "#d83d57",
    borderRadius: 20,
    minHeight: 64,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#d83d57",
    shadowOpacity: 0.38,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 9,
  },
  onboardingPrimaryButtonPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.96,
  },
  onboardingPrimaryButtonText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
  },
  onboardingModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(4,8,12,0.72)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  onboardingModalCard: {
    width: "100%",
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 16,
    backgroundColor: "#121c27",
    borderWidth: 1,
    borderColor: "#263241",
  },
  onboardingModalTitle: {
    color: "#f7f9fb",
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    textAlign: "center",
  },
  onboardingModalText: {
    color: "#97a4b3",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
    textAlign: "center",
  },
  onboardingModalActions: {
    gap: 10,
  },
  onboardingModalPrimaryButton: {
    minHeight: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#d83d57",
  },
  onboardingModalPrimaryText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  onboardingModalSecondaryButton: {
    minHeight: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1a2430",
    borderWidth: 1,
    borderColor: "#2a3746",
  },
  onboardingModalSecondaryText: {
    color: "#d7dde5",
    fontSize: 15,
    fontWeight: "800",
  },
  hero: {
    backgroundColor: "#295c41",
    borderRadius: 24,
    padding: 20,
    gap: 8,
  },
  debugCard: {
    backgroundColor: "#fff6de",
    borderRadius: 18,
    padding: 14,
    gap: 6,
    borderWidth: 1,
    borderColor: "#ead08e",
  },
  debugTitle: {
    color: "#6b4d06",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  debugLine: {
    color: "#5a471a",
    fontSize: 12,
    lineHeight: 18,
  },
  eyebrow: {
    color: "#d7efdc",
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontWeight: "700",
  },
  title: {
    color: "#ffffff",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
  },
  subtitle: {
    color: "#d4ead7",
    fontSize: 13,
  },
  card: {
    backgroundColor: "#fbfcf8",
    borderRadius: 22,
    padding: 16,
    gap: 14,
    shadowColor: "#0f2617",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  stepHeroCard: {
    backgroundColor: "#edf6ef",
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#d7e9dc",
  },
  stepHeroHeader: {
    gap: 4,
    flex: 1,
  },
  stepHeroEyebrow: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  stepHeroValue: {
    color: "#14301f",
    fontSize: 38,
    lineHeight: 42,
    fontWeight: "900",
  },
  stepHeroHint: {
    color: "#55715d",
    fontSize: 13,
    lineHeight: 18,
  },
  stepActivityBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#295c41",
    alignSelf: "flex-start",
  },
  stepActivityBadgeText: {
    color: "#ffffff",
    fontWeight: "800",
    textTransform: "uppercase",
    fontSize: 12,
    letterSpacing: 0.6,
  },
  stepProgressFill: {
    backgroundColor: "#2e7a51",
  },
  stepCoachHero: {
    backgroundColor: "#183527",
    borderRadius: 24,
    padding: 18,
    gap: 14,
  },
  stepCoachHeroHeader: {
    flex: 1,
    gap: 6,
  },
  stepCoachHeroEyebrow: {
    color: "#a9cbb4",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  stepCoachHeroValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: 8,
  },
  stepCoachHeroValue: {
    color: "#ffffff",
    fontSize: 36,
    lineHeight: 40,
    fontWeight: "900",
  },
  stepCoachHeroLabel: {
    color: "#d5e8da",
    fontSize: 15,
    fontWeight: "700",
    paddingBottom: 5,
  },
  stepCoachHeroSummary: {
    color: "#dbeadd",
    fontSize: 14,
    lineHeight: 20,
  },
  stepCoachHeroSupport: {
    color: "#ffffff",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
  },
  stepHeroStatRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  stepHeroStatPill: {
    flexBasis: "31%",
    flexGrow: 1,
    minWidth: 90,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    gap: 4,
  },
  stepHeroStatLabel: {
    color: "#b8d3c1",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  stepHeroStatValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  stepHeroActionStack: {
    gap: 10,
  },
  stepGuidanceCard: {
    backgroundColor: "#f8fbf6",
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  stepGuidanceActions: {
    gap: 10,
  },
  stepMilestoneGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  stepMilestoneCard: {
    flexBasis: "48%",
    flexGrow: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#f2f7f0",
    borderWidth: 1,
    borderColor: "#deeadf",
    gap: 4,
  },
  stepMilestoneCardReached: {
    backgroundColor: "#183527",
    borderColor: "#183527",
  },
  stepMilestoneTitle: {
    color: "#163423",
    fontSize: 14,
    fontWeight: "800",
  },
  stepMilestoneTitleReached: {
    color: "#ffffff",
  },
  stepMilestoneDetail: {
    color: "#6b7d70",
    fontSize: 12,
    fontWeight: "600",
  },
  stepMilestoneDetailReached: {
    color: "#b8d3c1",
  },
  stepMiniGoalList: {
    gap: 10,
  },
  stepMiniGoalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#f3f7f1",
    borderWidth: 1,
    borderColor: "#dfe9dd",
  },
  stepMiniGoalRowReached: {
    backgroundColor: "#edf6ef",
    borderColor: "#cfe3d3",
  },
  stepMiniGoalMark: {
    width: 14,
    height: 14,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#98b49f",
    backgroundColor: "transparent",
  },
  stepMiniGoalMarkReached: {
    backgroundColor: "#2e7a51",
    borderColor: "#2e7a51",
  },
  stepMiniGoalLabel: {
    flex: 1,
    color: "#173625",
    fontSize: 14,
    fontWeight: "700",
  },
  stepMiniGoalLabelReached: {
    color: "#173625",
  },
  stepMiniGoalState: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  walkSessionCard: {
    gap: 12,
  },
  walkPresetRow: {
    flexDirection: "row",
    gap: 10,
  },
  walkPresetChip: {
    flexBasis: "31%",
    flexGrow: 1,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#f3f7f1",
    borderWidth: 1,
    borderColor: "#dfe9dd",
  },
  walkPresetChipActive: {
    backgroundColor: "#183527",
    borderColor: "#183527",
  },
  walkPresetChipDisabled: {
    opacity: 0.8,
  },
  walkPresetText: {
    color: "#173625",
    fontSize: 14,
    fontWeight: "800",
  },
  walkPresetTextActive: {
    color: "#ffffff",
  },
  walkSessionLiveCard: {
    backgroundColor: "#183527",
    borderRadius: 22,
    padding: 18,
    gap: 12,
  },
  walkSessionTimer: {
    color: "#ffffff",
    fontSize: 40,
    lineHeight: 44,
    fontWeight: "900",
  },
  walkSessionTarget: {
    color: "#b8d3c1",
    fontSize: 14,
    fontWeight: "700",
  },
  walkSessionMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  walkSessionMetricPill: {
    flexBasis: "48%",
    flexGrow: 1,
    minWidth: 120,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    gap: 4,
  },
  walkSessionMetricLabel: {
    color: "#b8d3c1",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  walkSessionMetricValue: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
  },
  walkSessionActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  walkSessionActionItem: {
    flex: 1,
  },
  walkSessionSummaryCard: {
    backgroundColor: "#f7fbf5",
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  walkSessionHistoryList: {
    gap: 10,
  },
  walkSessionHistoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#f7fbf5",
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  walkSessionHistoryCopy: {
    flex: 1,
    gap: 4,
  },
  walkSessionHistoryStats: {
    alignItems: "flex-end",
    gap: 4,
  },
  walkSessionHistoryDate: {
    color: "#173625",
    fontSize: 14,
    fontWeight: "800",
  },
  walkSessionHistoryValue: {
    color: "#173625",
    fontSize: 14,
    fontWeight: "900",
  },
  walkSessionHistoryMeta: {
    color: "#6b7d70",
    fontSize: 12,
    fontWeight: "700",
  },
  motivationTaskCard: {
    backgroundColor: "#f7fbf5",
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  motivationTaskCopy: {
    flex: 1,
    gap: 4,
  },
  motivationStatusPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#ebf3ea",
  },
  motivationStatusPillDone: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#183527",
  },
  motivationStatusText: {
    color: "#55715d",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  motivationStatusTextDone: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  motivationProgressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#deeadf",
    overflow: "hidden",
  },
  motivationProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#2e7a51",
  },
  motivationMeta: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "700",
  },
  achievementGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  achievementCard: {
    flexBasis: "48%",
    flexGrow: 1,
    minWidth: 140,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#f3f7f1",
    borderWidth: 1,
    borderColor: "#dfe9dd",
    gap: 6,
  },
  achievementCardEarned: {
    backgroundColor: "#183527",
    borderColor: "#183527",
  },
  achievementTitle: {
    color: "#173625",
    fontSize: 14,
    fontWeight: "800",
  },
  achievementTitleEarned: {
    color: "#ffffff",
  },
  achievementDetail: {
    color: "#6b7d70",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  achievementDetailEarned: {
    color: "#b8d3c1",
  },
  achievementStateLocked: {
    color: "#55715d",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  achievementStateEarned: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  leaderboardCard: {
    backgroundColor: "#f7fbf5",
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  leaderboardList: {
    gap: 10,
  },
  leaderboardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#eef5ec",
  },
  leaderboardRank: {
    width: 34,
    color: "#173625",
    fontSize: 14,
    fontWeight: "900",
  },
  leaderboardName: {
    flex: 1,
    color: "#173625",
    fontSize: 14,
    fontWeight: "700",
  },
  leaderboardValue: {
    color: "#295c41",
    fontSize: 13,
    fontWeight: "900",
  },
  socialChallengeList: {
    gap: 10,
  },
  socialChallengeCard: {
    backgroundColor: "#f7fbf5",
    borderRadius: 18,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  socialGroupCard: {
    backgroundColor: "#f7fbf5",
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  socialGroupLeaderboard: {
    gap: 10,
  },
  socialGroupRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#eef5ec",
  },
  socialGroupRank: {
    width: 34,
    alignItems: "center",
  },
  socialGroupCopy: {
    flex: 1,
    gap: 2,
  },
  socialDuelChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#183527",
  },
  socialDuelChipText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  socialDuelCard: {
    backgroundColor: "#183527",
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  socialNotificationList: {
    gap: 10,
  },
  sectionBody: {
    gap: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#14301f",
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#dfeee1",
    color: "#295c41",
    fontWeight: "700",
    overflow: "hidden",
  },
  badgeSoft: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#edf3eb",
    color: "#59705e",
    fontSize: 12,
    overflow: "hidden",
  },
  inlineMetaGroup: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  field: {
    gap: 6,
    flexGrow: 1,
    minWidth: 140,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: "#31553a",
  },
  input: {
    borderWidth: 1,
    borderColor: "#c9d7c7",
    borderRadius: 14,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#14301f",
    fontSize: 15,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  optionChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#edf3eb",
  },
  optionChipActive: {
    backgroundColor: "#295c41",
  },
  optionChipText: {
    color: "#31553a",
    fontWeight: "700",
  },
  optionChipTextActive: {
    color: "#ffffff",
  },
  primaryButton: {
    backgroundColor: "#295c41",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryButtonSubtle: {
    backgroundColor: "#edf3eb",
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
  primaryButtonTextSubtle: {
    color: "#295c41",
  },
  messageBox: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  messageNeutral: {
    backgroundColor: "#edf3eb",
  },
  messageSuccess: {
    backgroundColor: "#dff3e2",
  },
  messageWarning: {
    backgroundColor: "#f8eed2",
  },
  messageError: {
    backgroundColor: "#f9dfdf",
  },
  messageText: {
    color: "#23412b",
    lineHeight: 20,
  },
  rewardOverlay: {
    position: "absolute",
    top: 94,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 40,
  },
  rewardOverlayPill: {
    minWidth: 124,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#152331",
    borderWidth: 1,
    borderColor: "#d83d57",
    shadowColor: "#d83d57",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  rewardOverlayPillRare: {
    borderColor: "#ffcc66",
    shadowColor: "#ffcc66",
    shadowOpacity: 0.26,
    shadowRadius: 20,
    elevation: 7,
  },
  rewardOverlayText: {
    color: "#ffffff",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  stepHistoryList: {
    gap: 10,
  },
  stepHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepHistoryLabel: {
    width: 34,
    color: "#55715d",
    fontWeight: "700",
    fontSize: 12,
  },
  stepHistoryTrack: {
    flex: 1,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#dceadf",
    overflow: "hidden",
  },
  stepHistoryFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#3f8a5f",
  },
  stepHistoryValue: {
    width: 58,
    textAlign: "right",
    color: "#173625",
    fontWeight: "700",
    fontSize: 12,
  },
  stepCheckpointList: {
    gap: 10,
  },
  stepCheckpointRow: {
    backgroundColor: "#f5f8f3",
    borderRadius: 16,
    padding: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: "#dfe7dc",
  },
  stepCheckpointHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  stepCheckpointLabel: {
    color: "#173625",
    fontSize: 14,
    fontWeight: "800",
  },
  stepCheckpointBadge: {
    color: "#3f8a5f",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  stepCheckpointMeta: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "600",
  },
  stepCheckpointHint: {
    color: "#173625",
    fontSize: 13,
    lineHeight: 18,
  },
  stepHourlyTimeline: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingTop: 8,
  },
  stepHourlyColumn: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  stepHourlyTrack: {
    width: "100%",
    height: 84,
    backgroundColor: "#dceadf",
    borderRadius: 12,
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  stepHourlyFill: {
    width: "100%",
    backgroundColor: "#3f8a5f",
    borderRadius: 12,
    minHeight: 2,
  },
  stepHourlyValue: {
    color: "#173625",
    fontSize: 10,
    fontWeight: "700",
  },
  stepHourlyLabel: {
    color: "#55715d",
    fontSize: 10,
    fontWeight: "700",
  },
  coachInsightGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metricCard: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: "#f1f6ef",
    borderRadius: 16,
    padding: 14,
    gap: 4,
  },
  metricLabel: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: "800",
    color: "#163423",
  },
  metricDetail: {
    color: "#59705e",
    fontSize: 13,
    lineHeight: 18,
  },
  block: {
    gap: 10,
  },
  blockTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#163423",
  },
  choiceCard: {
    backgroundColor: "#fff8ea",
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  choiceTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#523d10",
  },
  choiceQuestion: {
    color: "#6d5724",
    lineHeight: 20,
  },
  choiceChip: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbc78f",
  },
  choiceChipText: {
    color: "#624a16",
    fontWeight: "700",
  },
  itemCard: {
    backgroundColor: "#f8fbf6",
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#173625",
  },
  itemMeta: {
    color: "#5a7261",
    lineHeight: 20,
  },
  itemMacro: {
    color: "#295c41",
    fontWeight: "700",
    lineHeight: 20,
  },
  coachMessage: {
    color: "#173625",
    fontSize: 15,
    lineHeight: 22,
  },
  coachPriorityCard: {
    backgroundColor: "#173d2b",
    borderRadius: 22,
    padding: 18,
    gap: 14,
  },
  coachPriorityEyebrow: {
    color: "#bfe3ca",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  coachPriorityTitle: {
    color: "#ffffff",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  actionPillRow: {
    gap: 8,
  },
  actionPill: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  actionPillText: {
    color: "#eff9f1",
    lineHeight: 20,
    fontWeight: "700",
  },
  nextMealCard: {
    backgroundColor: "#f7fbf6",
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  nextMealLabel: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  nextMealValue: {
    color: "#173625",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "800",
  },
  riskControlRow: {
    gap: 6,
  },
  riskControlLabel: {
    color: "#bfe3ca",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  riskControlValue: {
    color: "#dcefe2",
    lineHeight: 20,
  },
  scoreHeroCard: {
    backgroundColor: "#eef7f0",
    borderRadius: 22,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#d4e7d8",
  },
  scoreHeroHeader: {
    gap: 2,
  },
  scoreHeroEyebrow: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  scoreHeroStatus: {
    color: "#295c41",
    fontSize: 14,
    fontWeight: "800",
  },
  scoreHeroValueWrap: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  scoreHeroValue: {
    color: "#173625",
    fontSize: 40,
    lineHeight: 40,
    fontWeight: "900",
  },
  scoreHeroUnit: {
    color: "#55715d",
    fontSize: 16,
    fontWeight: "800",
    paddingBottom: 4,
  },
  scoreTrack: {
    height: 10,
    backgroundColor: "#dceadf",
    borderRadius: 999,
    overflow: "hidden",
  },
  scoreFill: {
    height: "100%",
    borderRadius: 999,
  },
  scoreFillStrong: {
    backgroundColor: "#2e7a51",
  },
  scoreFillFair: {
    backgroundColor: "#b98928",
  },
  scoreFillFragile: {
    backgroundColor: "#c66049",
  },
  scoreHeroHint: {
    color: "#486251",
    lineHeight: 20,
  },
  scoreBreakdownRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  scoreBreakdownPill: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 92,
    gap: 2,
  },
  scoreBreakdownLabel: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "700",
  },
  scoreBreakdownValue: {
    color: "#173625",
    fontSize: 18,
    fontWeight: "800",
  },
  rewardCard: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: "#fffbf0",
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#ecdca5",
  },
  rewardEyebrow: {
    color: "#8b6a17",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  rewardGrid: {
    flexDirection: "row",
    gap: 8,
  },
  rewardPill: {
    flex: 1,
    backgroundColor: "#fffef9",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 4,
  },
  rewardValue: {
    color: "#5f4912",
    fontSize: 22,
    fontWeight: "900",
  },
  rewardLabel: {
    color: "#8b6a17",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  rewardHint: {
    color: "#7a6430",
    fontSize: 12,
    lineHeight: 18,
  },
  confidenceCard: {
    flexBasis: "48%",
    flexGrow: 1,
    backgroundColor: "#f6f9f5",
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#dde8dc",
  },
  confidenceEyebrow: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  confidenceValue: {
    color: "#173625",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "900",
    marginTop: 4,
  },
  confidenceTag: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  confidenceTagHigh: {
    backgroundColor: "#dff2e4",
  },
  confidenceTagMedium: {
    backgroundColor: "#f5e8c4",
  },
  confidenceTagLow: {
    backgroundColor: "#f7dede",
  },
  confidenceTagText: {
    color: "#173625",
    fontWeight: "800",
  },
  confidenceHint: {
    color: "#5a7261",
    lineHeight: 20,
  },
  supportCard: {
    backgroundColor: "#f8fbf6",
    borderRadius: 18,
    padding: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  emptyStateCard: {
    backgroundColor: "#f8fbf6",
    borderRadius: 18,
    padding: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: "#e1ece0",
  },
  manualStepCard: {
    backgroundColor: "#f5f8f3",
    borderRadius: 18,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: "#dfe7dc",
  },
  supportLabel: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  decisionCard: {
    backgroundColor: "#f0f7ed",
    borderRadius: 18,
    padding: 14,
    gap: 10,
  },
  decisionLine: {
    color: "#173625",
    lineHeight: 22,
  },
  decisionBlock: {
    gap: 4,
  },
  decisionLabel: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  decisionValue: {
    color: "#173625",
    lineHeight: 21,
    fontWeight: "700",
  },
  dashboardHero: {
    borderRadius: 28,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    shadowColor: "#0f2617",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  dashboardHookCard: {
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 8,
    backgroundColor: "#152331",
    borderWidth: 1,
    borderColor: "#d83d57",
    shadowColor: "#d83d57",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  dashboardHookEyebrow: {
    color: "#f4a9b5",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  dashboardHookHint: {
    color: "#ffd7de",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  dashboardHookTitle: {
    color: "#ffffff",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  dashboardHeroNeutral: {
    backgroundColor: "#eff6f0",
    borderColor: "#d7e6da",
  },
  dashboardHeroStrong: {
    backgroundColor: "#eff6f0",
    borderColor: "#cfe2d4",
  },
  dashboardHeroFair: {
    backgroundColor: "#fff8ea",
    borderColor: "#ecd8a1",
  },
  dashboardHeroFragile: {
    backgroundColor: "#fbefed",
    borderColor: "#ebc7bf",
  },
  dashboardHeroHeader: {
    flex: 1,
    gap: 4,
  },
  dashboardEyebrow: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  dashboardStatus: {
    color: "#295c41",
    fontSize: 14,
    fontWeight: "800",
  },
  dashboardIdentityTitle: {
    color: "#173625",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  proCard: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "#d8caa0",
  },
  proBadge: {
    color: "#7a5a12",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  proCopy: {
    gap: 2,
  },
  proText: {
    color: "#6a5d33",
    fontSize: 12,
    fontWeight: "700",
  },
  proSubtext: {
    color: "#8a7a47",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
  },
  dashboardStreakWrap: {
    gap: 4,
    paddingTop: 6,
    paddingBottom: 2,
  },
  dashboardStreakText: {
    color: "#1d4a31",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
  },
  dashboardLevelLabel: {
    color: "#55715d",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  levelTrack: {
    width: "100%",
    height: 6,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(29,74,49,0.12)",
  },
  levelFill: {
    height: "100%",
    borderRadius: 999,
  },
  levelFillLow: {
    backgroundColor: "#7b9884",
  },
  levelFillMid: {
    backgroundColor: "#4f7a5d",
  },
  levelFillHigh: {
    backgroundColor: "#2f6a48",
  },
  dashboardLevelMeta: {
    color: "#68806f",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  dashboardLevelPreview: {
    color: "#819182",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  dashboardStreakBroken: {
    color: "#9d3636",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
  },
  dashboardStreakHint: {
    color: "#55715d",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  dashboardRewardCard: {
    backgroundColor: "rgba(255,255,255,0.8)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 2,
    borderWidth: 1,
    borderColor: "#d7e6da",
  },
  dashboardRewardTitle: {
    color: "#173625",
    fontSize: 14,
    fontWeight: "800",
  },
  dashboardRewardDetail: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "700",
  },
  dashboardSocialProof: {
    backgroundColor: "rgba(255,255,255,0.62)",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e6dc",
  },
  dashboardSocialProofText: {
    color: "#486251",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  dashboardSocialProofHint: {
    color: "#738473",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  dashboardShareAction: {
    alignSelf: "flex-start",
    minWidth: 132,
  },
  hiddenShareCapture: {
    position: "absolute",
    left: -9999,
    top: -9999,
    width: 320,
    opacity: 0,
  },
  shareCard: {
    width: 320,
    backgroundColor: "#173d2b",
    borderRadius: 28,
    padding: 24,
    gap: 10,
    borderWidth: 1,
    borderColor: "#2e7a51",
  },
  shareCardEyebrow: {
    color: "#d4ead7",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  shareCardValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  shareCardValue: {
    color: "#ffffff",
    fontSize: 62,
    lineHeight: 62,
    fontWeight: "900",
  },
  shareCardUnit: {
    color: "#d7efdc",
    fontSize: 18,
    fontWeight: "800",
    paddingBottom: 8,
  },
  shareCardTitle: {
    color: "#ffffff",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
  },
  shareCardMessage: {
    color: "#d4ead7",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  shareCardFooter: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(212,234,215,0.18)",
    gap: 2,
  },
  shareCardInvite: {
    display: "none",
  },
  shareCardCta: {
    color: "#ffffff",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
  },
  shareCardBrand: {
    color: "#d4ead7",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  dashboardScoreWrap: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  dashboardScoreValue: {
    color: "#163423",
    fontSize: 46,
    lineHeight: 46,
    fontWeight: "900",
  },
  dashboardScoreUnit: {
    color: "#55715d",
    fontSize: 16,
    fontWeight: "800",
    paddingBottom: 5,
  },
  dashboardPriorityCard: {
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 18,
    padding: 14,
    gap: 4,
  },
  dashboardPriorityLabel: {
    color: "#55715d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  dashboardPriorityValue: {
    color: "#163423",
    fontSize: 16,
    fontWeight: "800",
  },
  dashboardProfilePrompt: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: "#d7e6da",
  },
  dashboardMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  dashboardMetricItem: {
    flexBasis: "48%",
    flexGrow: 1,
  },
  dashboardWarningCard: {
    backgroundColor: "#fbe8e8",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: "#e3b2b2",
  },
  dashboardWarningTitle: {
    color: "#922f2f",
    fontSize: 15,
    fontWeight: "800",
  },
  dashboardWarningText: {
    color: "#7a3b3b",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  progressPulse: {
    borderRadius: 24,
    shadowColor: "#66b06d",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    transform: [{ scale: 1.01 }],
  },
  dashboardPrimeMessage: {
    color: "#173625",
    fontSize: 15,
    lineHeight: 22,
  },
  dashboardActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  dashboardActionItem: {
    flexBasis: "31%",
    flexGrow: 1,
    minWidth: 100,
  },
  mutedText: {
    color: "#6d8073",
    lineHeight: 20,
  },
  mealConfidenceBadge: {
    backgroundColor: "#e8f1e7",
    color: "#295c41",
    fontWeight: "700",
  },
  errorText: {
    color: "#9d3636",
    lineHeight: 20,
  },
});

export default styles;
