/**
 * @file postureLLMSchema.js
 * @description Standardized data definitions for the LLM Preparation Layer (Layer 5).
 */

export const PostureLLMSchema = {
  createLLMContextPacket: () => ({
    postureContext: {
      current: {
        status: "",
        score: null,
        confidence: "low",
        quality: "low",
        limitedMode: false,
        viewsUsed: [],
        primaryFocus: null,
        secondaryFocus: null,
        signals: [] // Array of curated signals { type, severity, confidence, sourceViews }
      },
      trend: {
        overall: "unknown",
        signalTrends: {}
      },
      baseline: {
        trusted: false,
        baselineScore: null
      },
      capture: {
        issues: [],
        mostReliableAngle: null
      },
      explainability: {
        focusExplanation: {}
      }
    }
  }),

  createLLMSafetyGuards: () => ({
    lowConfidenceGuard: false,
    limitedModeGuard: false,
    weakEvidenceGuard: false,
    noDiagnosisGuard: true, // Always true strictly
    trendGuard: false,
    medicalEscalationFlag: false
  }),

  createLLMInputPacket: () => ({
    systemContext: PostureLLMSchema.createLLMContextPacket(),
    safetyGuards: PostureLLMSchema.createLLMSafetyGuards(),
    baseKnowledgeOutput: {} // Fallback strings generated by Layer 3 directly, allows LLM to just spice them up or override
  }),

  // What the LLM MUST return
  createResponseContract: () => ({
    summary: "",
    focusMessage: "",
    coachingMessage: "",
    confidenceMessage: "",
    trendMessage: "",
    captureMessage: "" // optional
  })
};
